### PR TITLE
Fixed memory deallocation on windows.

### PR DESCRIPTION
**Pull request by NunaticAlumina**

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi there @NunaticAlumina , 

would it be possible to use libretro-common memalign/memfree functions instead of straight memalign and friends?

https://github.com/libretro/RetroArch/blob/master/libretro-common/memmap/memalign.c

Maybe some ifdefs are necessary for Vita but I think it should work across Windows/LInux/OSX at least.

Right now the code fails for OSX due to 1) lack of malloc.h header, and 2) lack of memalign.

**Comment by twinaphex** [comment]
@NunaticAlumina  Our buildbot also reports this error upon trying to compile VBA Next for Vita - 

http://hastebin.com/ucazeconum

Any ideas?

**Comment by frangarcj** [comment]
It's better to use -O3 with -fno-optimize-sibling-calls

**Comment by NunaticAlumina** [comment]
@frangarcj I removed other options too.
@twinaphex Gonna fix it.

**Pull request merged**
