### PR TITLE
Adding X and Y Buttons as extra keys for L and R

### PR DESCRIPTION
**Pull request by LodanZark**
Adding X and Y Buttons as extra keys for L and R which is very handy for certain games specially fighting and fast paced action alike street fighter alpha 3 and sonic battle

### CODE REVIEW

**Comment by fr500** [comment]
You can alter the mapping with core input remapping. In any case this
should be an option not a default behavior

**Comment by LodanZark** [comment]
There is no issues or whatsoever, this change already happened in lr-gpsp and there is no negative reports neither complaints, it's important preserve  the L and R buttons in their default mapping in situations that requires press L+A or R+B alike metroid games, and some games are better using the X Y instead R L because the buttons are closer, I am not removing the traditional mapping, I am giving more options and bring the best from both worlds specially since buttons X and R are not being used, plus would be a mess adding core input remapping for each different game.

**Comment by twinaphex** [comment]
Alright, I dont see much wrong with this.

**Comment by twinaphex** [comment]
Actually, thinking about it, it doesn't make much sense and having two conflicting L/R bound keys as input descriptors causes bad conflicts. So reverting this entirely.

**Pull request merged**
