### PR TITLE
Threaded renderer - further improvement.

### PR DESCRIPTION
**Pull request by NunaticAlumina**
now multiple threads can be used on rendering.

### CODE REVIEW

**Comment by twinaphex** [comment]
@NunaticAlumina I'm getting some compilation errors for some of the non-Vita platforms -

http://hastebin.com/irosalarim

Can you fix this?

**Comment by orbea** [comment]
I'm getting this too now.
https://github.com/libretro/vba-next/issues/54

**Comment by twinaphex** [comment]
Pushed a temporary workaround for this until @NunaticAlumina comes up with a better fix I guess since I don't know what the rampakWaitState function calls are supposed to -

https://github.com/libretro/vba-next/commit/80b4ca6b7a96b9d0e790a4c38b55573c8ae04d90

**Comment by orbea** [comment]
Thanks, I will leave my issue in place until a better solution is found.

**Pull request merged**
